name: Lint

on:

  push:
    branches:
      - main

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
 strategy:
      matrix:
        node-version: [18.x]
  steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
      # Install your linters here

      uses: actions/setup-node@v1
        # The Node.js version to configure
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        # Install project
        run: |
          make install
        # Add environment variables
        env:
          CI: true
      - name: Run linter
        # Run Linter
        run: |
          make lint
          